### ISSUE TITLE
Use only on product pages?

### ISSUE THREAD

**Issue by jimlakey** [dimitri-koenig/magento-pjax#4]
Hey Dimitri,

I assume if I change the container from `body` to something like `#pjax-container` in run.js:

`$(document).pjax('[data-pjax] a, a[data-pjax]', 'body', pjaxOptions);`

I can use pjax just in templates of my choosing rather than everywhere on the Magento site?

If you have a minute to reply, I'd really appreciate it. Thank you!

**Comment by jimlakey** [comment]
The answer to my first question is just to use the data attributes on the links you want PJAX to work on. But then I also wanted to just ajax in a section of a page, not all of it. As long as it is the only section (HTML el, that is), changing line 84 of Observer.php to:

`$content = preg_replace('/.*(<title>.*<\/title>).*<section id="pjax-container"[^>]*>(.*)<\/section>.*/is', '$1$2', $content);`

and run.js to:

`$(document).pjax('[data-pjax] a, a[data-pjax]', '#pjax-container', pjaxOptions);`

works fine. This way you can just pull in the content needed rather than full body with header and footer etc.

So this is no longer an issue. Thanks.

**Comment by badi238** [comment]
i am doing same but my js is not working now on product page like wishlist and color swatches these js are not working now

**Comment by heswebs** [comment]
Can this be used on Magento 2? or if there are any other better alternatives?

**Comment by dimitri-koenig** [comment]
Nope, Magento 2 has a different architecture. And I don't know about any alternatives

**Comment by heswebs** [comment]
Ty for the reply. Just got it work xD very nice!

**Comment by dimitri-koenig** [comment]
Really? Would you like to provide a PR? I guess there are some others who could benefit from your work
